export type Lang = 'EN' | 'FR';

export const damageDice: Record<Lang, string[]> = {
  EN: [
    'No Damage !',
    'No Damage !',
    'One Damage !',
    'Two Damage !',
    'Damage Effect !',
    'Damage Effect !',
  ],
  FR: [
    'Pas de dégâts !',
    'Pas de dégâts !',
    'Un dégât !',
    'Deux dégâts !',
    'Effet spécial et dégâts !',
    'Effet spécial et dégâts',
  ],
};

export const locationDice: Record<Lang, string[]> = {
  EN: [
    'Head',
    'Head',
    'Torso',
    'Torso',
    'Torso',
    'Torso',
    'Torso',
    'Torso',
    'Left Arm',
    'Left Arm',
    'Left Arm',
    'Right Arm',
    'Right Arm',
    'Right Arm',
    'Left Leg',
    'Left Leg',
    'Left Leg',
    'Right Leg',
    'Right Leg',
    'Right Leg',
  ],
  FR: [
    'Tête',
    'Tête',
    'Torse',
    'Torse',
    'Torse',
    'Torse',
    'Torse',
    'Torse',
    'Bras gauche',
    'Bras gauche',
    'Bras gauche',
    'Bras droit',
    'Bras droit',
    'Bras droit',
    'Jambe gauche',
    'Jambe gauche',
    'Jambe gauche',
    'Jambe droite',
    'Jambe droite',
    'Jambe droite',
  ],
};